---
# https://circleci.com/developer/orbs/orb/circleci/terraform
version: '2.1'
orbs: 
  terraform: circleci/terraform@3.1.0
workflows:
  deploy_infrastructure:
    jobs:
      - terraform/validate:
          checkout: true
          context: tflab
      - terraform/plan:
          checkout: true
          context: tflab
          persist-workspace: true
          requires:
            - terraform/validate     
      - terraform/apply:
          attach-workspace: true
          context: tflab
          filters:
            branches:
              only: master
          requires:
            - terraform/plan
